version: '3.7'
services:
    synology-make-px4_drv:
#        build:
#            context: .
        container_name: syno-make-px4_drv
        image: collelog/synology-make-px4_drv
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./results_file:/toolkit/results_file
        network_mode: "bridge"
        init: true
        tty: true
